version: '3.8'

services:
  app:
    image: novus_crm
    container_name: novus_crm
    restart: always
    ports:
      - "8080:8080"
    environment:
       - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/novus_crm?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
       - SPRING_DATASOURCE_USERNAME=root
       - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: novus_crm
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./conf/mysql/init/:/docker-entrypoint-initdb.d/
    # networks:
    #   - novus_crm_network # docker compose will create the network for services automatically


  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  mysql_data:
