spring:
  application:
    name: NovusCRM
  datasource:
    url: jdbc:mysql://localhost:3306/novus
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB # max file upload size
      max-request-size: 100MB
  devtools:
    restart:
      enabled: true # or use Hotswap of Idea instead
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/public/
        - classpath:/resources/
        - classpath:/META-INF/resources/
        - file:///C:/Users/Boris/Documents/10_MyGithub/demo/resources/images

project:
  resource:
    static-locations:
      images: file:///C:/Users/Boris/Documents/10_MyGithub/demo/resources/images

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mappers/*.xml

#springdoc:
#  swagger-ui:
#    path: /swagger
#  api-docs:
#    path: /docs

pagehelper:
  reasonable: true # if start page <= 0, make it = 1
  helper-dialect: mysql

#spring事务管理日志
#logging:
#  level:
#    org.springframework.jdbc.support.JdbcTransactionManager: debug
